<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                'nom' => 'esteban',
                'email' => 'esteban@gmail.com',
                'password' => '$2y$12$29MUXvqInTh8VZABlt02qu2youdoIYIb4/ylNrb0FAkwpcrL21Equ', // hashed password
                'role' => 'admin',
                'created_at' => '2024-07-15 06:02:08',
                'updated_at' => '2024-07-16 17:02:38',
            ],
            [
                'nom' => 'John Doe',
                'email' => 'john.doe1@example.com',
                'password' => bcrypt('password'), // hashed password
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Jane Smith',
                'email' => 'jane.smith2@example.com',
                'password' => bcrypt('password'), // hashed password
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Alice Johnson',
                'email' => 'alice.johnson3@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Bob Brown',
                'email' => 'bob.brown4@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Charlie Davis',
                'email' => 'charlie.davis5@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Eve Martinez',
                'email' => 'eve.martinez6@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Frank Wilson',
                'email' => 'frank.wilson7@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Grace Lee',
                'email' => 'grace.lee8@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Hank White',
                'email' => 'hank.white9@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Ivy Harris',
                'email' => 'ivy.harris10@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Jack Clark',
                'email' => 'jack.clark11@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Kelly Lewis',
                'email' => 'kelly.lewis12@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Larry Young',
                'email' => 'larry.young13@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Megan King',
                'email' => 'megan.king14@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Nina Hall',
                'email' => 'nina.hall15@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Oscar Allen',
                'email' => 'oscar.allen16@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Paula Martinez',
                'email' => 'paula.martinez17@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Quincy Brown',
                'email' => 'quincy.brown18@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Rachel Green',
                'email' => 'rachel.green19@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Sam Taylor',
                'email' => 'sam.taylor20@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Tom Harris',
                'email' => 'tom.harris21@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Ursula King',
                'email' => 'ursula.king22@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Victor White',
                'email' => 'victor.white23@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Wendy Davis',
                'email' => 'wendy.davis24@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Xavier Brown',
                'email' => 'xavier.brown25@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Yvonne Lewis',
                'email' => 'yvonne.lewis26@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Zack Taylor',
                'email' => 'zack.taylor27@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Anna King',
                'email' => 'anna.king28@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Benjamin White',
                'email' => 'benjamin.white29@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Cindy Martinez',
                'email' => 'cindy.martinez30@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'David Brown',
                'email' => 'david.brown31@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Emily Harris',
                'email' => 'emily.harris32@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Fred Taylor',
                'email' => 'fred.taylor33@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Gina Lewis',
                'email' => 'gina.lewis34@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Henry Clark',
                'email' => 'henry.clark35@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Isabel King',
                'email' => 'isabel.king36@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Jake White',
                'email' => 'jake.white37@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Kelly Martinez',
                'email' => 'kelly.martinez38@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Linda Brown',
                'email' => 'linda.brown39@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Mike Harris',
                'email' => 'mike.harris40@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Nancy Taylor',
                'email' => 'nancy.taylor41@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Oliver Lewis',
                'email' => 'oliver.lewis42@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Paula Clark',
                'email' => 'paula.clark43@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Quincy King',
                'email' => 'quincy.king44@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Rachel White',
                'email' => 'rachel.white45@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Samuel Harris',
                'email' => 'samuel.harris46@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Tammy Clark',
                'email' => 'tammy.clark47@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Ursula King',
                'email' => 'ursula.king48@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Victor Brown',
                'email' => 'victor.brown49@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Wendy Harris',
                'email' => 'wendy.harris50@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Xavier Lewis',
                'email' => 'xavier.lewis51@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Yvonne Clark',
                'email' => 'yvonne.clark52@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
            [
                'nom' => 'Zack Harris',
                'email' => 'zack.harris53@example.com',
                'password' => bcrypt('password'),
                'role' => 'user',
                'created_at' => '2024-07-16 07:52:16',
                'updated_at' => '2024-07-16 07:52:16',
            ],
        ];

        // Insert users into database
        foreach ($users as $user) {
            User::create($user);
        }
    }
}
